version: '3.8'
services:
  centos_clean:
    image: perfsonar/dev-centos-clean:latest
    build:
        context: .
        dockerfile: Dockerfile
    tmpfs: 
       - /run
       - /tmp
    volumes:
       - /sys/fs/cgroup:/sys/fs/cgroup:ro
    ports:
       - "8443:443"
